### ISSUE TITLE
Unable to execute API - TypeError: Cannot read property 'access_token' of undefined

### ISSUE THREAD

**Issue by marcschregardus** [XeroAPI/xero-node-oauth2-app#10]
I've followed the instructions in the readme, but I'm unable to successfully execute any of the API's locally, and receive the error message below:

<img width="581" alt="Screen Shot 2019-12-19 at 12 42 10 pm" src="https://user-images.githubusercontent.com/1586747/71137914-d7708580-225d-11ea-8bc7-9490e9ffd1ec.png">

I have my own (live) company, and a demo company, and I'm connecting to the demo company (from the list of available options). I have tried disconnecting and reconnecting the company, as well as clearing the cache, cookies, using an incognito browser, etc. The following warning also occurs when the app starts up:

<img width="574" alt="Screen Shot 2019-12-19 at 12 41 09 pm" src="https://user-images.githubusercontent.com/1586747/71138031-3504d200-225e-11ea-8251-4aa060da5c6b.png">
 
Any pointers to get the demo app up and running?

Thanks,

Marc

**Comment by marcschregardus** [comment]
The problem appears to be with the `REDIRECT_URI` variable - which requires `callback` to be appended. I.e. 

`REDIRECT_URI=http://localhost:${PORT}/callback`

Or using the default port of 5000,

`REDIRECT_URI=http://localhost:5000/callback`

I.e.

<img width="488" alt="Screen Shot 2019-12-19 at 1 15 21 pm" src="https://user-images.githubusercontent.com/1586747/71139217-a85c1300-2261-11ea-801f-004997310f1d.png">

**Comment by SerKnight** [comment]
Hi @marcschregardus - thanks for you issue. Fixed so others won't wast time on this. Glad you got it fixed and hope the sample app is helpful getting you up to speed. Also noted that there are still a few endpoints I need to complete.

I added an error that throws if all the required ENV vars are not set.

> https://github.com/XeroAPI/xero-node-oauth2-app/blob/master/src/app.ts#L75
