### ISSUE TITLE
Error: Cannot find module '../xeroBankFeedClient'

### ISSUE THREAD

**Issue by ghost** [XeroAPI/xero-node-oauth2-app#11]
Trying to run the project but i get this error 
Error: Cannot find module '../xeroBankFeedClient' also if the module is correctly installed.
Do you know what is the problem?

**Comment by SerKnight** [comment]
So https://github.com/XeroAPI/xero-node-bankfeeds is a separate repo.. The sdk is open source, but that specific api access is actually monitored more than the normal accounting API and needs additional access.. Have it in this repo as will eventually expand for some example calls with it as well.

Are you unable to download the package? ( https://www.npmjs.com/package/xero-node-bankfeeds ) @neiroc

**Comment by candrasaputra** [comment]
i have same issue.

i already try install xero node bankfeeds manualy (npm i xero-node-bankfeeds).

**Comment by SerKnight** [comment]
Hi all - removing the bank feeds code for now - Bank Feeds is a closed API ( https://developer.xero.com/documentation/bank-feeds-api/overview ) if you feel like your business falls in the criteria to access please inquire @ https://developer.xero.com/partner/app-partner and you can discuss your use case with your local Developer Evangelist.
