### ISSUE TITLE
issue in access_token refresh_token

### ISSUE THREAD

**Issue by Zubair-Ashraf** [XeroAPI/xero-node-oauth2-app#24]
I want to generate invoices with the help of API endpoints but for that need access_token.
I tested all sample codes of OAuth 2.0 from github repo's but all of that works when go to browser connect with xero account then i am getting access_token but i need token without going to browser or clicking buttons.
Is any API endpoint is available that i hit with client_id, client_secret or that API give me token ?

**Comment by MattR-Api** [comment]
Hi @Zubair-Ashraf

As this isn't a a xero-node specific issue, we'll shut this issue down.

However, to answer your question, when using OAuth 2.0 you will need to use the web based authentication system for the initial connection, just like you currently do with Partner or Public OAuth 1.0a Apps and similar to how you need to be invited into the Organisation you're connecting a Private App too.

Once this has been established and authenticated by a user, if you've included the offline_access scope in your Authentication, your app will benefit from access tokens that can be renewed without user intervention, but a user must manually authenticate the initial Connection.

For more information, please see the link below. I've also included a link to a blog post explaining some of our thoughts and reasoning.

Xero Developer:
[The OAuth Flow](https://developer.xero.com/documentation/oauth2/auth-flow)
[Xero Blog](https://devblog.xero.com/an-update-on-why-we-are-saying-goodbye-oauth-1-0a-hello-oauth-2-0-6a839230908f)

If you need any more information, please feel free to get in touch with us at api@xero.com.

Kind Regards

Matt
