### ISSUE TITLE
Error when connecting application to Xero with default scopes

### ISSUE THREAD

**Issue by ajmueller** [XeroAPI/xero-node-oauth2-app#33]
When connecting the application to Xero with the default scopes, I see the following error:

![image](https://user-images.githubusercontent.com/1442179/75698877-54f44100-5c64-11ea-98e2-74d942f54ffb.png)

I contacted API support and they told me to remove the `paymentservices` scope and to try again.  That fixed the issue and I was able to immediately connect to Xero.

I'm not sure what the underlying issue is, whether that's a scope that I don't have access to based on my role in my Xero orgs or if it's a restricted scope that only certain orgs have access to, but it would be helpful to have this fix documented here.  I'm happy to open a PR to update the documentation if that is an acceptable fix.

**Comment by RettBehrens** [comment]
hey @ajmueller you're right, that's a restricted scope and it's since been removed from the default list of scopes.
