### ISSUE TITLE
Cannot try this app

### ISSUE THREAD

**Issue by josemalvarezg1** [XeroAPI/xero-node-oauth2-app#34]
Hi! Whenever I log into my Xero account and then allow access to this app, I get this error:
RPError: JWT not active yet, now 1583604078, nbf 1583604307

![image](https://user-images.githubusercontent.com/19997251/76150074-afced380-607c-11ea-9f80-b5b96a60efab.png)

**Comment by RettBehrens** [comment]
hey @josemalvarezg1 I'm unable to reproduce this. Can you double check which xero-node version you're running? It should be 4.4.3. 

If it continues to be an issue, reopen this issue and we'll explore it further

**Comment by lightwavebusiness** [comment]
I had the same issue, only resolution was to change line 45 of XeroClient.js from:
                this.openIdClient[openid_client_1.custom.clock_tolerance] = 5
to
                this.openIdClient[openid_client_1.custom.clock_tolerance] = 50

Hope this helps others.
