### ISSUE TITLE
README has invalid information

### ISSUE THREAD

**Issue by andrui** [XeroAPI/xero-node-oauth2-app#45]
Hi!

> Enter your app details (your redirect URI: http://localhost:${PORT})

I fact(according to the app code) redirect url should be http://localhost:${PORT}/callback

**Comment by SerKnight** [comment]
Thanks Adrui!

Changed readme to `Enter your app details (your redirect URI: http://localhost:${PORT}/your-callback-route)` 

Hope that helps the next person quicker :)
