### ISSUE TITLE
Verification failed while extracting xero-node@4.6.0:

### ISSUE THREAD

**Issue by vishal112logistic** [XeroAPI/xero-node-oauth2-app#50]
Node version: v12.16.3
Os : mac 10.14.1

Just get clone as readme, update .env and build run and getting this error: 
npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting xero-node@4.6.0:
npm ERR! Verification failed while extracting xero-node@4.6.0:
npm ERR! sha512-yn5aTswnUftXAsfHNait/aG8YGLBdOZOfb3RW0nAdgfJo5S2eO06cVJzPxRyPQzJAtySU2NvAqBF6yM1faXFew== integrity checksum failed when using sha512: wanted sha512-yn5aTswnUftXAsfHNait/aG8YGLBdOZOfb3RW0nAdgfJo5S2eO06cVJzPxRyPQzJAtySU2NvAqBF6yM1faXFew== but got sha512-LWU1HOJrzYkpVxfSCCILrNXPcUjtIznMWmUNRTH5ky3PgG9n3o6iliH6uHOEcVGB+pwfl+bpFMbGa2bddpG3Vg==. (1568560 bytes)

Let me know if you require more information.

**Comment by harrisonsuarez** [comment]
Same happened for me. I was able to resolve with:

```
npm uninstall --save xero-node
npm install --save xero-node
```

**Comment by vishal112logistic** [comment]
@harrisonsuarez 
Thanks for your replay, i am using https://github.com/XeroAPI/xero-node-oauth2-ts-starter now it's batter and working fine.
