### ISSUE TITLE
Update readme to warn against using real xero account

### ISSUE THREAD

**Issue by mbyrne00** [XeroAPI/xero-node-oauth2-app#8]
Thanks for this app - it certainly helps with solid examples.

Although the readme suggests to "Create a free Xero user account (if you don't have one)" it doesn't make it clear that by clicking a link in the navbar it will create, update, delete items. People ordinarily expect buttons to update/delete.

That's fine and it's all an example but it would be nice to add a warning so that people don't have their real xero data updated by the sample app.

Apologies if I've misunderstood how it works.

**Comment by SerKnight** [comment]
This is a great call out. I will make it much more explicit ASAP

**Comment by SerKnight** [comment]
Going out in a PR today - thanks for your activity. Will be addressing your concerns in the Core SDK ASAP I can get the time in the coming weeks.

![Screen Shot 2019-12-18 at 11 49 05 AM](https://user-images.githubusercontent.com/2935387/71114221-8fcdf900-218c-11ea-8589-f340a2eca7e8.png)
![Screen Shot 2019-12-18 at 11 48 32 AM](https://user-images.githubusercontent.com/2935387/71114223-8fcdf900-218c-11ea-97e2-8ea9c342f7cb.png)


Happy holidays mate!

**Comment by mbyrne00** [comment]
Great stuff - thanks @SerKnight! Enjoy the break.
